FROM apache/dolphinscheduler-worker:3.2.2

# 更新包列表并安装所需软件
RUN apt-get update && \
    apt-get install -y \
    python3 \
    openjdk-8-jdk \
    jq \
    vim \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# 添加环境变量到 /etc/profile
RUN echo "export PYTHON_LAUNCHER=/usr/bin/python3" >> /etc/profile && \
    echo "export DATAX_LAUNCHER=/opt/soft/datax/bin/datax.py" >> /etc/profile